# Generated by Django 5.2.11 on 2026-03-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_annotatorbucketassignment_video_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assigned_s3_path',
            field=models.CharField(blank=True, default='', help_text='Assigned source for this user, e.g. s3://bucket/path, bucket/path, local path, or direct video URL.', max_length=1024),
        ),
    ]
