# Generated by Django 4.2 on 2026-03-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_label_library_and_project_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('annotator', 'Annotator'), ('reviewer', 'Reviewer'), ('assigner', 'Assigner'), ('surverour_head', 'Surverour Head')], default='annotator', max_length=20),
        ),
        migrations.CreateModel(
            name='AnnotatorURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1024)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('annotator', models.OneToOneField(limit_choices_to={'role': 'annotator'}, on_delete=django.db.models.deletion.CASCADE, related_name='annotator_url', to='accounts.customuser')),
            ],
            options={
                'verbose_name': 'Annotator URL',
                'verbose_name_plural': 'Annotator URLs',
                'ordering': ['annotator__django_user__username'],
            },
        ),
    ]
