# Generated by Django 4.2 on 2026-03-16 08:32

from django.db import migrations, models


def _rename_role_forward(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(role='surverour_head').update(role='surveyor_head')


def _rename_role_backward(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(role='surveyor_head').update(role='surverour_head')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_role_annotatorurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('annotator', 'Annotator'), ('reviewer', 'Reviewer'), ('assigner', 'Assigner'), ('surveyor_head', 'Surveyor Head')], default='annotator', max_length=20),
        ),
        migrations.RunPython(_rename_role_forward, _rename_role_backward),
    ]
