# Generated by Django 4.2 on 2026-03-16 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=1024, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='annotatorurl',
            name='resource',
            field=models.ForeignKey(blank=True, help_text='Optional reference to a reusable URL entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotator_urls', to='accounts.urlresource'),
        ),
    ]
